### ISSUE TITLE
I would like to also have the following

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AMereBagatelle/Thresher#1]
Optifine = Tested / Untested 
Shaderpacks = Working / Not Working
GPU Minimum
CPU Minimum

**Comment by P3rf3ctXZer0** [comment]
Recommended forge version

**Comment by AMereBagatelle** [comment]
GPU and CPU minimum are planned, however how do you mean shaderpack testing?  Also, what do you mean by Optifine being tested?  As in testing if optifine exists?

**Comment by AMereBagatelle** [comment]
Also, a forge port may or may not happen, it would be a goal only once I am done with feature additions to this mod.  Personally I prefer Fabric, but it would be nice to support Forge sometime in the future.

**Comment by P3rf3ctXZer0** [comment]
Okay so just something simple like 
Config 
Optifine Ready - True : False Version - Name of optine jar manually typed in

If true a water mark in the right corner of title screen should say 

"This pack is optifine ready. It was last test with "Name of manual jar name here" "

**Comment by AMereBagatelle** [comment]
I may do that if I make a forge port.  However, I am not interested in doing so on fabric, as the optifine developer has restricted people from putting optifine in modpacks to begin with.  I suggest the Sodium mod instead, which offers far better performance and is able to be distributed in modpacks.

**Comment by P3rf3ctXZer0** [comment]
I only use forge.

**Comment by P3rf3ctXZer0** [comment]
the reason you would add optifine watermark is so people know they can download it and safely add it to the pack.

**Comment by P3rf3ctXZer0** [comment]
I don't distribute optifine.
